service: bref-runtime-demo

custom:
    stage: ${opt:stage, "dev"}
    region: eu-central-1

provider:
    name: aws
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    runtime: provided.al2
    memorySize: 1792
    deploymentBucket:
        name: nyholm-lambda-applications
    deploymentPrefix: com.subtreesplit/${sls:instanceId}
    environment:
        APP_ENV: prod
        APP_RUNTIME: App\Runtime\BrefRuntime
        BREF_LOOP_MAX: 3

plugins:
    - ./vendor/bref/bref

functions:
    symfony:
        handler: public/index.php
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74}
            - arn:aws:lambda:eu-central-1:403367587399:layer:bref-symfony-runtime:3
        events:
            -   httpApi: 'GET /'

    psr:
        handler: public/psr.php
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74}
            - arn:aws:lambda:eu-central-1:403367587399:layer:bref-symfony-runtime:3
        events:
            -   httpApi: 'GET /psr'

    container:
        handler: public/container.php:App\MyHandler
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74}
            - arn:aws:lambda:eu-central-1:403367587399:layer:bref-symfony-runtime:3
        events:
            -   httpApi: 'GET /container'


    console:
        handler: bin/console
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74}
            - arn:aws:lambda:eu-central-1:403367587399:layer:bref-symfony-runtime:3

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
