service: bref-runtime-demo

custom:
    stage: ${opt:stage, "dev"}
    region: eu-central-1

provider:
    name: aws
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    runtime: provided.al2
    memorySize: 1792
    deploymentBucket:
        name: nyholm-lambda-applications
    deploymentPrefix: com.subtreesplit/${sls:instanceId}
    environment:
        APP_ENV: prod
        BREF_AUTOLOAD_PATH: /var/task/public/index.php
        APP_RUNTIME: App\Runtime\BrefRuntime

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74}
        events:
            -   httpApi: '*'

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
