service: bref-runtime-demo

custom:
    stage: ${opt:stage, "dev"}
    region: eu-central-1

provider:
    name: aws
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    runtime: provided.al2
    deploymentBucket:
        name: nyholm-lambda-applications
    deploymentPrefix: com.subtreesplit/${sls:instanceId}

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 8
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   httpApi: '*'

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
