service: bref-runtime-demo

custom:
    stage: ${opt:stage, "dev"}
    region: eu-central-1

provider:
    name: aws
    region: ${self:custom.region}
    stage: ${self:custom.stage}
    runtime: provided.al2
    memorySize: 1792
    deploymentBucket:
        name: nyholm-lambda-applications
    environment:
        APP_ENV: prod
        APP_RUNTIME: Runtime\Bref\Runtime
        BREF_LOOP_MAX: 3

plugins:
    - ./vendor/runtime/bref-layer

functions:
    symfony:
        handler: public/index.php
        description: ''
        timeout: 8
        layers:
            - ${runtime-bref:php-80}
        events:
            -   httpApi: 'GET /'
            -   httpApi: 'GET /foo'

    psr:
        handler: public/psr.php
        description: ''
        timeout: 8
        layers:
            - ${runtime-bref:php-80}
        events:
            -   httpApi: 'GET /psr'

    container:
        handler: public/container.php:App\MyHandler
        description: ''
        timeout: 8
        layers:
            - ${runtime-bref:php-80}
        events:
            -   httpApi: 'GET /container'

    console:
        handler: bin/console
        description: ''
        timeout: 3
        layers:
            - ${runtime-bref:php-80}

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
