index:
    path: /
    controller: App\Controller\HelloController::index

foo:
    path: /foo
    controller: App\Controller\HelloController::foo

timeout:
    path: /timeout
    controller: App\Controller\HelloController::timeout
